### ISSUE TITLE
CSS issues with index.css

### ISSUE THREAD

**Issue by gabrielbrise** [gabrielbrise/cwallet#7]
Issue when viewing cwallet in https://cwallet.herokuapp.com/

Console shows an error related to the loading of the index.css file.

Problem is easily noticed by the wrong primary color (blue instead of orange).

`Refused to apply style from 'https://cwallet.herokuapp.com/index.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by DineshKoushik** [comment]
@gabrielbrise , can I try this?

**Comment by DineshKoushik** [comment]
@gabrielbrise , can you provide readme please, i'm getting errors while starting the app

**Comment by gabrielbrise** [comment]
Sure, I'll write one. You are probably missing the env vars needed.

**Comment by gabrielbrise** [comment]
@DineshKoushik done, I've created a README, I hope it works for you

**Comment by DineshKoushik** [comment]
Hi @gabrielbrise , have you resolved this issue? because I'm not getting any errors in console in the local.

**Comment by gabrielbrise** [comment]
Not yet, seems to happen only in the herokuapp. Maybe running the build in production mode could simulate this locally. I'll try to fix it when I have time but it is not a huge issue. Have you managed to run the application locally with no problems?

**Comment by DineshKoushik** [comment]
@gabrielbrise , Yeah, I'm now able to run the application in call perfectly fine. But strangely, I'm not able to see any errors regarding index.css file.

**Comment by gabrielbrise** [comment]
solved in commit 4599df9359402296d6b269bbd3d5adbd297de132
I was serving the static public files in the wrong way for production
